### ISSUE TITLE
Localization possible ?

### ISSUE THREAD

**Issue by dionmes** [sebischair/Lbl2Vec#2]
Does Lbl2Vec work with other languages than English, as in does it create the doc2vec correctly when using it on other languages ?

**Comment by TimSchopf** [comment]
If you learn a new Lbl2Vec model from scratch, this also trains a Doc2Vec model from scratch internally. This approach is language agnostic. Therefore, you can apply Lbl2Vec to data of any language. However, I cannot predict how well Lbl2Vec actually works in other languages, since we have only evaluated in English so far. The performance most likely depends on the complexity of the language as well as on the preprocessing of the data.

**Comment by dionmes** [comment]
Thanks Tim, makes sense. Gonna look for some Dutch docs 👍
